mlm:
	cat mlm.json | faas-cli invoke bert-base | faas-cli invoke bert-mlm

nsp:
	cat nsp.json | faas-cli invoke bert-base | faas-cli invoke bert-nsp
	
qa:
	cat qa.json | faas-cli invoke bert-base | faas-cli invoke bert-qa

sa:
	cat sa.json | faas-cli invoke bert-base | faas-cli invoke bert-sa

ner:
	cat ner.json | faas-cli invoke bert-base | faas-cli invoke bert-ner

mlm-imdb:
	cat mlm-imdb.json | faas-cli invoke bert-base | faas-cli invoke bert-mlm-imdb | faas-cli invoke bert-mlm
